service: ${self:custom.service}
frameworkVersion: "3"

custom: ${file(config/serverless/common-custom-config.yaml)}

provider:
  name: aws
  runtime: nodejs20.x
  memorySize: 1024
  versionFunctions: false
  stage: ${opt:stage, self:custom.defaultStage}
  region: ${self:custom.regions.code.${opt:stage}}
  logRetentionInDays: 5
  deploymentPrefix: serverless
  environment:
    NASA_API_KEY: ''
    CACHE_TTL: 1800
  lambdaHashingVersion: 20201221
plugins:
  - serverless-plugin-typescript
  - serverless-plugin-optimize
  - serverless-offline
  - serverless-jetpack

functions: ${file(config/serverless/functions.${self:custom.functionsFile}.yml)}

